
version: 2.1

orbs:
  slack: circleci/slack@4.3.1

jobs:
  Hello:
    docker:
      - image: docker:18.09.3-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: echo hello world
          command: |
            echo "Hello World"
      - slack/notify:
          channel: C0233P8D42J
          event: pass
          template: basic_success_1
      - slack/notify:
          channel: C0233P8D42J
          event: fail
          template: basic_fail_1   

  Deployment:
    docker:
      - image: docker:18.09.3-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Install dependencies
          command: |
            echo "Hello from Circleci" 
      - slack/notify:
          channel: C0233P8D42J
          event: pass
          template: basic_success_1
      - slack/notify:
          channel: C0233P8D42J
          event: fail
          template: basic_fail_1   


workflows:
  version: 2
  build_and_deploy_stage:
    jobs:
      - Hello:
          filters:
            branches:
              only: circleci-project-setup

      - Deployment:
          requires:
            - Hello
          filters:
            branches:
              only: circleci-project-setup

